### ISSUE TITLE
Do we change server?

### ISSUE THREAD

**Issue by hsumyatm7308** [hsumyatm7308/gitlesson3#3]
n publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder before final copy is available. It is also used to temporarily replace text in a process called greeking, which allows designers to consider the form of a webpage or publication,

**Comment by H-zai** [comment]
Okay as you like ><
